# Generated by Django 6.0.4 on 2026-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0007_rename_cikis_gumruk_is_bekleme_faturasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='odeme_durumu',
            field=models.CharField(choices=[('Bekleniyor', 'Bekleniyor'), ('Kısmi Ödeme', 'Kısmi Ödeme'), ('Ödendi', 'Ödendi')], default='Bekleniyor', max_length=50),
        ),
        migrations.AlterField(
            model_name='is',
            name='durum',
            field=models.CharField(choices=[('Teklif', 'Teklif'), ('Aktif İş', 'Aktif İş'), ('Planlandı', 'Planlandı'), ('Yüklemede', 'Yüklemede'), ('Yüklendi', 'Yüklendi'), ('Yolda', 'Yolda'), ('Limanda', 'Limanda'), ('Boşaltmada', 'Boşaltmada'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Teklif', max_length=50),
        ),
    ]
