# Generated by Django 6.0.4 on 2026-05-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0010_rename_tasima1_turu_is_arac_tipi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='derece_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='is',
            name='derece_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='is',
            name='gumruk_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/gumruk/'),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_gelen_fatura',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_gelen_fatura_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_gelen_fatura',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_gelen_fatura_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='teminat_ayri_fatura_no',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='teminat_satisa_dahil_mi',
            field=models.CharField(choices=[('Hayır', 'Hayır'), ('Evet', 'Evet')], default='Evet', max_length=10),
        ),
    ]
