# Generated by Django 6.0.4 on 2026-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0011_is_derece_max_is_derece_min_is_gumruk_evraklari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='para_birimi',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='is',
            name='derece_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='is',
            name='derece_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
