# Generated by Django 6.0.4 on 2026-05-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0012_is_para_birimi_alter_is_derece_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(blank=True, max_length=200)),
                ('sofor_adi', models.CharField(blank=True, max_length=200)),
                ('plaka', models.CharField(blank=True, max_length=100)),
                ('sorun_tipi', models.CharField(choices=[('Gecikme', 'Gecikme'), ('Evrak Sorunu', 'Evrak Sorunu'), ('Hasar', 'Hasar'), ('İletişim Kötü', 'İletişim Kötü'), ('Ödeme Sorunu', 'Ödeme Sorunu'), ('Sahte Bilgi', 'Sahte Bilgi'), ('Diğer', 'Diğer')], default='Diğer', max_length=50)),
                ('aciklama', models.TextField(blank=True)),
                ('tarih', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='is',
            name='guncel_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='ikinci_guncel_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='ikinci_nakliyeci',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='is',
            name='nakliyeci',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='is',
            name='notlar',
            field=models.TextField(blank=True),
        ),
    ]
