# Generated by Django 6.0.4 on 2026-05-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0013_riskkaydi_is_guncel_konum_is_ikinci_guncel_konum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_gelen_fatura_tutari',
            new_name='elden_verilen_avans',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_gelen_fatura_tutari',
            new_name='yapilan_odeme',
        ),
    ]
