# Generated by Django 6.0.4 on 2026-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0015_is_tasima1_gelen_fatura_tutari_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='is',
            name='elden_verilen_avans',
        ),
        migrations.RemoveField(
            model_name='is',
            name='yapilan_odeme',
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_elden_verilen_avans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_yapilan_odeme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_elden_verilen_avans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_yapilan_odeme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
