# Generated by Django 6.0.4 on 2026-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0016_remove_is_elden_verilen_avans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='nakliyeci_notu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='is',
            name='risk_notu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='is',
            name='sofor_notu',
            field=models.TextField(blank=True),
        ),
    ]
