# Generated by Django 6.0.4 on 2026-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0017_is_nakliyeci_notu_is_risk_notu_is_sofor_notu'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='risk_durumu',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
