# Generated by Django 6.0.4 on 2026-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Is',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('durum', models.CharField(max_length=50)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
