# Generated by Django 6.0.4 on 2026-04-29 08:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20)),
                ('surucu', models.CharField(max_length=100)),
                ('yuk_aciklama', models.TextField()),
                ('cikis', models.CharField(max_length=100)),
                ('varis', models.CharField(max_length=100)),
                ('durum', models.CharField(default='Yolda', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='is',
            options={'ordering': ['-sira_no'], 'verbose_name': 'İş Kaydı', 'verbose_name_plural': 'İş Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='is',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='is',
            name='musteri',
        ),
        migrations.RemoveField(
            model_name='is',
            name='tarih',
        ),
        migrations.AddField(
            model_name='is',
            name='aktarma_masrafi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Aktarma Masrafı'),
        ),
        migrations.AddField(
            model_name='is',
            name='aktarma_plaka',
            field=models.CharField(blank=True, max_length=50, verbose_name='Aktarma Yapılacak Plaka'),
        ),
        migrations.AddField(
            model_name='is',
            name='alis_fatura1_no',
            field=models.CharField(blank=True, max_length=120, verbose_name='1. Alış Fatura No'),
        ),
        migrations.AddField(
            model_name='is',
            name='alis_fatura1_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='1. Alış Fatura Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='alis_fatura2_no',
            field=models.CharField(blank=True, max_length=120, verbose_name='2. Alış Fatura No'),
        ),
        migrations.AddField(
            model_name='is',
            name='alis_fatura2_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='2. Alış Fatura Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='arac_tipi',
            field=models.CharField(blank=True, choices=[('Mega', 'Mega'), ('Tenteli', 'Tenteli'), ('Lowbed', 'Lowbed'), ('Sal Kasa', 'Sal Kasa'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Lorry', 'Lorry')], max_length=30, verbose_name='Araç Tipi'),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma1_konumu',
            field=models.CharField(blank=True, max_length=255, verbose_name='1. Boşaltma Konumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma1_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='1. Boşaltma Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma2_konumu',
            field=models.CharField(blank=True, max_length=255, verbose_name='2. Boşaltma Konumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma2_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2. Boşaltma Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='cikan_teminat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Çıkan Teminat'),
        ),
        migrations.AddField(
            model_name='is',
            name='derece_araligi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Derece Aralığı'),
        ),
        migrations.AddField(
            model_name='is',
            name='diger_maliyet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Diğer Maliyet'),
        ),
        migrations.AddField(
            model_name='is',
            name='dozvala_masrafi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='DOZVALA Masrafı'),
        ),
        migrations.AddField(
            model_name='is',
            name='fatura_bedeli',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Fatura Bedeli'),
        ),
        migrations.AddField(
            model_name='is',
            name='fatura_kesildi_mi',
            field=models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=10, verbose_name='Kesilen Fatura Durumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='gelen_fatura',
            field=models.FileField(blank=True, null=True, upload_to='evrak/gelen_fatura/', verbose_name='Gelen Fatura'),
        ),
        migrations.AddField(
            model_name='is',
            name='gelen_fatura_odeme',
            field=models.CharField(choices=[('Ödendi', 'Ödendi'), ('Ödenmedi', 'Ödenmedi')], default='Ödenmedi', max_length=20, verbose_name='Gelen Fatura Ödeme Durumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='gemi_adi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gemi Adı'),
        ),
        migrations.AddField(
            model_name='is',
            name='gemi_kalkis_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gemi Kalkış Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='gemi_tahliye_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gemi Tahliye Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='gumruk_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evrak/gumruk/', verbose_name='Gümrük Evrakları'),
        ),
        migrations.AddField(
            model_name='is',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='hat',
            field=models.CharField(choices=[('EU/RU', 'EU/RU'), ('TR/RU', 'TR/RU'), ('RU/TR', 'RU/TR'), ('KZ/TR', 'KZ/TR'), ('TR/KZ', 'TR/KZ'), ('EU/KZ', 'EU/KZ')], default='TR/RU', max_length=20, verbose_name='Hat / Güzergah'),
        ),
        migrations.AddField(
            model_name='is',
            name='isin_adi',
            field=models.CharField(default='test', max_length=255, verbose_name='İşin Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is',
            name='kesilen_fatura',
            field=models.FileField(blank=True, null=True, upload_to='evrak/kesilen_fatura/', verbose_name='Kesilen Fatura'),
        ),
        migrations.AddField(
            model_name='is',
            name='kesilen_fatura_no',
            field=models.CharField(blank=True, max_length=120, verbose_name='Kesilen Fatura No'),
        ),
        migrations.AddField(
            model_name='is',
            name='liman_cikis_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Limandan Çıkış Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='liman_masraflari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Liman Masrafları'),
        ),
        migrations.AddField(
            model_name='is',
            name='notlar',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='is',
            name='odeme_notu',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ödeme Notu'),
        ),
        migrations.AddField(
            model_name='is',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is',
            name='plaka',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plaka'),
        ),
        migrations.AddField(
            model_name='is',
            name='satis_para_birimi',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='EUR', max_length=3, verbose_name='Satış Para Birimi'),
        ),
        migrations.AddField(
            model_name='is',
            name='satis_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Satış Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='sira_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Sıra No'),
        ),
        migrations.AddField(
            model_name='is',
            name='sofor_adi',
            field=models.CharField(blank=True, max_length=120, verbose_name='Şoför Adı'),
        ),
        migrations.AddField(
            model_name='is',
            name='sofor_numarasi',
            field=models.CharField(blank=True, max_length=120, verbose_name='Şoför Numarası'),
        ),
        migrations.AddField(
            model_name='is',
            name='tahsilat_durumu',
            field=models.CharField(choices=[('Tahsil Edildi', 'Tahsil Edildi'), ('Tahsil Edilmedi', 'Tahsil Edilmedi')], default='Tahsil Edilmedi', max_length=30, verbose_name='Satış Tahsilat Durumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='telefon',
            field=models.CharField(blank=True, max_length=120, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='is',
            name='teminat_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Teminat Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='teslim_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evrak/teslim/', verbose_name='Teslim Evrakları'),
        ),
        migrations.AddField(
            model_name='is',
            name='tuapse_ardiye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tuapse Ardiye Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='tuapse_bekleme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tuapse Bekleme Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='tuapse_cikis_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tuapse Çıkış Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='tuapse_evrak_teslim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tuapse Evrak Teslim Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='turkiye_ardiye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Türkiye Ardiye Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='usd_eur_parite',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.9200'), max_digits=10, verbose_name='USD → EUR Paritesi'),
        ),
        migrations.AddField(
            model_name='is',
            name='vade_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Vade Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme1_bekleme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='1. Yükleme Bekleme Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme1_konumu',
            field=models.CharField(blank=True, max_length=255, verbose_name='1. Yükleme Konumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme1_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='1. Yükleme Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme1_varis_gumrugu',
            field=models.CharField(blank=True, max_length=255, verbose_name='1. Yükleme Varış Gümrüğü'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme2_bekleme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='2. Yükleme Bekleme Tutarı'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme2_konumu',
            field=models.CharField(blank=True, max_length=255, verbose_name='2. Yükleme Konumu'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme2_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2. Yükleme Tarihi'),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme2_varis_gumrugu',
            field=models.CharField(blank=True, max_length=255, verbose_name='2. Yükleme Varış Gümrüğü'),
        ),
        migrations.AddField(
            model_name='is',
            name='yurtdisi_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evrak/yurtdisi/', verbose_name='Yurtdışı Evrakları'),
        ),
        migrations.AlterField(
            model_name='is',
            name='durum',
            field=models.CharField(choices=[('Planlandı', 'Planlandı'), ('Yüklemede', 'Yüklemede'), ('Yükledi evrak bekliyor', 'Yükledi evrak bekliyor'), ('Yolda', 'Yolda'), ('Limanda', 'Limanda'), ('Boşaltma bekliyor', 'Boşaltma bekliyor'), ('Boşaldı', 'Boşaldı'), ('İptal', 'İptal')], default='Planlandı', max_length=50, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='Evrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='evraklar/')),
                ('yuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takip.yuk')),
            ],
        ),
    ]
