# Generated by Django 6.0.4 on 2026-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0003_alter_is_options_remove_is_aktarma_masrafi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='kar_zarar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='is',
            name='musteri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
