# Generated by Django 6.0.4 on 2026-04-30 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0004_is_kar_zarar_alter_is_musteri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is',
            old_name='bosaltma1_tarih',
            new_name='tasima1_bosaltma_tarihi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='bosaltma1_yer',
            new_name='tasima1_cikis',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='plaka',
            new_name='tasima1_plaka',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='sofor_adi',
            new_name='tasima1_sofor',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='sofor_tel',
            new_name='tasima1_sofor_tel',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='bosaltma2_yer',
            new_name='tasima1_varis',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='bosaltma2_tarih',
            new_name='tasima1_yukleme_tarihi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tuapse_cikis',
            new_name='tasima2_bosaltma_tarihi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='yukleme1_yer',
            new_name='tasima2_cikis',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='yukleme2_yer',
            new_name='tasima2_varis',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tuapse_varis',
            new_name='tasima2_yukleme_tarihi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='yukleme1_tarih',
            new_name='teklif_gecerlilik_tarihi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='yukleme2_tarih',
            new_name='teklif_tarihi',
        ),
        migrations.RemoveField(
            model_name='is',
            name='arac_tipi',
        ),
        migrations.RemoveField(
            model_name='is',
            name='kar_zarar',
        ),
        migrations.RemoveField(
            model_name='is',
            name='maliyet',
        ),
        migrations.RemoveField(
            model_name='is',
            name='satis',
        ),
        migrations.RemoveField(
            model_name='is',
            name='tuapse_ardiye',
        ),
        migrations.AddField(
            model_name='is',
            name='diger_evrak',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/'),
        ),
        migrations.AddField(
            model_name='is',
            name='gumruk_evraki',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/'),
        ),
        migrations.AddField(
            model_name='is',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='is',
            name='kayit_tipi',
            field=models.CharField(choices=[('Teklif', 'Teklif'), ('Aktif İş', 'Aktif İş'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Teklif', max_length=30),
        ),
        migrations.AddField(
            model_name='is',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is',
            name='para_birimi',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_maliyet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_satis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_turu',
            field=models.CharField(blank=True, choices=[('Tenteli', 'Tenteli'), ('Mega', 'Mega'), ('Sal Kasa', 'Sal Kasa'), ('Lowbed', 'Lowbed'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Lorry', 'Lorry'), ('Parsiyel', 'Parsiyel'), ('20DC', '20DC'), ('40DC', '40DC'), ('40HC', '40HC'), ('45HC', '45HC'), ('Open Top', 'Open Top'), ('Flat Rack', 'Flat Rack'), ('Hava Kargo', 'Hava Kargo'), ('Deniz LCL', 'Deniz LCL'), ('Deniz FCL', 'Deniz FCL'), ('Ro-Ro', 'Ro-Ro'), ('Gemiye Dökme', 'Gemiye Dökme'), ('Breakbulk', 'Breakbulk'), ('Tren', 'Tren'), ('Konteyner + Tır', 'Konteyner + Tır')], max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_maliyet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_plaka',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_satis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_sofor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_sofor_tel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_turu',
            field=models.CharField(blank=True, choices=[('Tenteli', 'Tenteli'), ('Mega', 'Mega'), ('Sal Kasa', 'Sal Kasa'), ('Lowbed', 'Lowbed'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Lorry', 'Lorry'), ('Parsiyel', 'Parsiyel'), ('20DC', '20DC'), ('40DC', '40DC'), ('40HC', '40HC'), ('45HC', '45HC'), ('Open Top', 'Open Top'), ('Flat Rack', 'Flat Rack'), ('Hava Kargo', 'Hava Kargo'), ('Deniz LCL', 'Deniz LCL'), ('Deniz FCL', 'Deniz FCL'), ('Ro-Ro', 'Ro-Ro'), ('Gemiye Dökme', 'Gemiye Dökme'), ('Breakbulk', 'Breakbulk'), ('Tren', 'Tren'), ('Konteyner + Tır', 'Konteyner + Tır')], max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='teklif_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='teslim_evraki',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/'),
        ),
        migrations.AddField(
            model_name='is',
            name='yuk_tanimi',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='is',
            name='durum',
            field=models.CharField(choices=[('Teklif', 'Teklif'), ('Planlandı', 'Planlandı'), ('Yüklemede', 'Yüklemede'), ('Yüklendi evrak bekliyor', 'Yüklendi evrak bekliyor'), ('Yolda', 'Yolda'), ('Gümrükte', 'Gümrükte'), ('Limanda', 'Limanda'), ('Boşaltma bekliyor', 'Boşaltma bekliyor'), ('Boşaldı', 'Boşaldı'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Teklif', max_length=50),
        ),
        migrations.AlterField(
            model_name='is',
            name='hat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='is',
            name='musteri',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
