# Generated by Django 6.0.4 on 2026-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0005_rename_bosaltma1_tarih_is_tasima1_bosaltma_tarihi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_bosaltma_tarihi',
            new_name='bosaltma1_tarih',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_yukleme_tarihi',
            new_name='bosaltma2_tarih',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='teklif_no',
            new_name='gtip_hs',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_bosaltma_tarihi',
            new_name='yukleme1_tarih',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_yukleme_tarihi',
            new_name='yukleme2_tarih',
        ),
        migrations.RemoveField(
            model_name='is',
            name='isin_adi',
        ),
        migrations.RemoveField(
            model_name='is',
            name='teklif_gecerlilik_tarihi',
        ),
        migrations.RemoveField(
            model_name='is',
            name='teklif_tarihi',
        ),
        migrations.AddField(
            model_name='is',
            name='aktarma_masrafi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='alici',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='is',
            name='ayri_fatura_aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='is',
            name='ayri_fatura_edilecek_mi',
            field=models.CharField(choices=[('Hayır', 'Hayır'), ('Evet', 'Evet')], default='Hayır', max_length=10),
        ),
        migrations.AddField(
            model_name='is',
            name='ayri_fatura_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='bekleme_masrafi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma1_adres',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma1_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma2_adres',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma2_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma_bekleme_baslangic',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma_bekleme_bitis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='is',
            name='cikis_gumruk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='is',
            name='diger_masraf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='elektronik_masraf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='gonderici',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='is',
            name='gumruk_masrafi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='gunluk_bekleme_ucreti',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='guzergah',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='is',
            name='is_kodu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='isin_kimden_alindigi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='is',
            name='kap_palet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='kilo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='liman_masrafi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='masraf_aciklama',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='is',
            name='ucretsiz_bekleme_saati',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='is',
            name='varis_gumruk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='is',
            name='varis_gumruk_evrak_kisi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='is',
            name='yuk_olculeri',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme1_adres',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme1_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme2_adres',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme2_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_bekleme_baslangic',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_bekleme_bitis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima1_cikis',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima1_plaka',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima1_sofor_tel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima1_turu',
            field=models.CharField(blank=True, choices=[('Tenteli', 'Tenteli'), ('Mega', 'Mega'), ('Sal Kasa', 'Sal Kasa'), ('Lowbed', 'Lowbed'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Parsiyel', 'Parsiyel'), ('20DC', '20DC'), ('40DC', '40DC'), ('40HC', '40HC'), ('45HC', '45HC'), ('Open Top', 'Open Top'), ('Flat Rack', 'Flat Rack'), ('Hava Kargo', 'Hava Kargo'), ('Deniz LCL', 'Deniz LCL'), ('Deniz FCL', 'Deniz FCL'), ('Ro-Ro', 'Ro-Ro'), ('Gemiye Dökme', 'Gemiye Dökme'), ('Breakbulk', 'Breakbulk'), ('Tren', 'Tren'), ('Konteyner + Tır', 'Konteyner + Tır')], max_length=50),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima1_varis',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima2_cikis',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima2_plaka',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima2_sofor_tel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima2_turu',
            field=models.CharField(blank=True, choices=[('Tenteli', 'Tenteli'), ('Mega', 'Mega'), ('Sal Kasa', 'Sal Kasa'), ('Lowbed', 'Lowbed'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Parsiyel', 'Parsiyel'), ('20DC', '20DC'), ('40DC', '40DC'), ('40HC', '40HC'), ('45HC', '45HC'), ('Open Top', 'Open Top'), ('Flat Rack', 'Flat Rack'), ('Hava Kargo', 'Hava Kargo'), ('Deniz LCL', 'Deniz LCL'), ('Deniz FCL', 'Deniz FCL'), ('Ro-Ro', 'Ro-Ro'), ('Gemiye Dökme', 'Gemiye Dökme'), ('Breakbulk', 'Breakbulk'), ('Tren', 'Tren'), ('Konteyner + Tır', 'Konteyner + Tır')], max_length=50),
        ),
        migrations.AlterField(
            model_name='is',
            name='tasima2_varis',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
