# Generated by Django 6.0.4 on 2026-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0008_is_odeme_durumu_alter_is_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='bosaltma_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/bosaltma/'),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima1_turu',
            field=models.CharField(blank=True, choices=[('Tenteli', 'Tenteli'), ('Mega', 'Mega'), ('Sal Kasa', 'Sal Kasa'), ('Lowbed', 'Lowbed'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Lorry', 'Lorry'), ('Parsiyel', 'Parsiyel'), ('20DC', '20DC'), ('40DC', '40DC'), ('Hava Kargo', 'Hava Kargo'), ('Gemiye Dökme', 'Gemiye Dökme')], max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_turu',
            field=models.CharField(blank=True, choices=[('Tenteli', 'Tenteli'), ('Mega', 'Mega'), ('Sal Kasa', 'Sal Kasa'), ('Lowbed', 'Lowbed'), ('Frigo', 'Frigo'), ('Minivan', 'Minivan'), ('Lorry', 'Lorry'), ('Parsiyel', 'Parsiyel'), ('20DC', '20DC'), ('40DC', '40DC'), ('Hava Kargo', 'Hava Kargo'), ('Gemiye Dökme', 'Gemiye Dökme')], max_length=50),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/yukleme/'),
        ),
        migrations.AddField(
            model_name='is',
            name='yurtdisi_evraklari',
            field=models.FileField(blank=True, null=True, upload_to='evraklar/yurtdisi/'),
        ),
    ]
