# Generated by Django 6.0.4 on 2026-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0009_is_bosaltma_evraklari_is_tasima1_turu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_turu',
            new_name='arac_tipi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='bekleme_faturasi_tutari',
            new_name='bosaltma_bekleme_diger_tutar',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_bosaltma_evrak_teslim_tarihi',
            new_name='bosaltma_evrak_teslim_zamani',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_bosaltma_konumu',
            new_name='bosaltma_konum',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_bosaltma_ucretsiz_saat',
            new_name='bosaltma_ucretsiz_saat',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_bosaltma_tarihi',
            new_name='bosaltma_zamani',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='bekleme_satis_tutari',
            new_name='elektronka_bedeli',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='ek_satis_tutari',
            new_name='fatura_edilecek_teminat_tutari',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='gelen_fatura1_tutari',
            new_name='fatura_tutari',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='gelen_fatura2_tutari',
            new_name='gelen_fatura_tutari',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='satis_tutari',
            new_name='gemi_faturasi_tutari',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_gerceklesen_yukleme',
            new_name='gerceklesen_yukleme_zamani',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_plaka',
            new_name='gtip',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_gelen_fatura_tutari',
            new_name='hesaplanan_teminat',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_turu',
            new_name='ikinci_arac_tipi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_gelen_fatura_tutari',
            new_name='ikinci_bosaltma_bekleme_diger_tutar',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_planlanan_yukleme',
            new_name='ikinci_bosaltma_evrak_teslim_zamani',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_yukleme_konumu',
            new_name='ikinci_bosaltma_konum',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_yukleme_ucretsiz_saat',
            new_name='ikinci_bosaltma_ucretsiz_saat',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_gerceklesen_zaman',
            new_name='ikinci_bosaltma_zamani',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_planlanan_zaman',
            new_name='ikinci_gerceklesen_yukleme_zamani',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_sofor_adi',
            new_name='ikinci_plaka',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima1_sofor_numarasi',
            new_name='ikinci_sofor_adi',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_plaka',
            new_name='ikinci_sofor_no',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='teminat_faturasi_tutari',
            new_name='ikinci_yukleme_bekleme_diger_tutar',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_yukleme_konumu',
            new_name='ikinci_yukleme_konum',
        ),
        migrations.RenameField(
            model_name='is',
            old_name='tasima2_ucretsiz_saat',
            new_name='ikinci_yukleme_ucretsiz_saat',
        ),
        migrations.RemoveField(
            model_name='is',
            name='bekleme_faturasi',
        ),
        migrations.RemoveField(
            model_name='is',
            name='gelen_fatura1',
        ),
        migrations.RemoveField(
            model_name='is',
            name='gelen_fatura2',
        ),
        migrations.RemoveField(
            model_name='is',
            name='notlar',
        ),
        migrations.RemoveField(
            model_name='is',
            name='tasima1_bekleme_ucreti',
        ),
        migrations.RemoveField(
            model_name='is',
            name='tasima1_gelen_fatura',
        ),
        migrations.RemoveField(
            model_name='is',
            name='tasima2_bekleme_ucreti',
        ),
        migrations.RemoveField(
            model_name='is',
            name='tasima2_gelen_fatura',
        ),
        migrations.RemoveField(
            model_name='is',
            name='teminat_faturasi',
        ),
        migrations.AddField(
            model_name='is',
            name='bosaltma_bekleme_ucreti',
            field=models.CharField(choices=[('100 USD', '100 USD'), ('150 USD', '150 USD'), ('200 USD', '200 USD'), ('250 USD', '250 USD'), ('300 USD', '300 USD'), ('100 EUR', '100 EUR'), ('150 EUR', '150 EUR'), ('200 EUR', '200 EUR'), ('250 EUR', '250 EUR'), ('300 EUR', '300 EUR'), ('Diğer', 'Diğer')], default='100 USD', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='esya_cinsi',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='is',
            name='gelen_fatura_numarasi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='gelen_gemi_faturasi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='ikinci_bosaltma_bekleme_ucreti',
            field=models.CharField(choices=[('100 USD', '100 USD'), ('150 USD', '150 USD'), ('200 USD', '200 USD'), ('250 USD', '250 USD'), ('300 USD', '300 USD'), ('100 EUR', '100 EUR'), ('150 EUR', '150 EUR'), ('200 EUR', '200 EUR'), ('250 EUR', '250 EUR'), ('300 EUR', '300 EUR'), ('Diğer', 'Diğer')], default='100 USD', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='ikinci_planlanan_yukleme_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='is',
            name='ikinci_tasima_var_mi',
            field=models.CharField(choices=[('Hayır', 'Hayır'), ('Evet', 'Evet')], default='Hayır', max_length=10),
        ),
        migrations.AddField(
            model_name='is',
            name='ikinci_yukleme_bekleme_ucreti',
            field=models.CharField(choices=[('100 USD', '100 USD'), ('150 USD', '150 USD'), ('200 USD', '200 USD'), ('250 USD', '250 USD'), ('300 USD', '300 USD'), ('100 EUR', '100 EUR'), ('150 EUR', '150 EUR'), ('200 EUR', '200 EUR'), ('250 EUR', '250 EUR'), ('300 EUR', '300 EUR'), ('Diğer', 'Diğer')], default='100 USD', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='kap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='kg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='liman_bekleme_diger_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='liman_bekleme_ucreti',
            field=models.CharField(choices=[('100 USD', '100 USD'), ('150 USD', '150 USD'), ('200 USD', '200 USD'), ('250 USD', '250 USD'), ('300 USD', '300 USD'), ('100 EUR', '100 EUR'), ('150 EUR', '150 EUR'), ('200 EUR', '200 EUR'), ('250 EUR', '250 EUR'), ('300 EUR', '300 EUR'), ('Diğer', 'Diğer')], default='100 USD', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='liman_ucretsiz_saat',
            field=models.IntegerField(choices=[(24, '24 Saat'), (48, '48 Saat'), (72, '72 Saat')], default=24),
        ),
        migrations.AddField(
            model_name='is',
            name='plaka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='planlanan_yukleme_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='is',
            name='satis_faturasi',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='is',
            name='satis_faturasi_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='sofor_adi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='sofor_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_bekleme_diger_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_bekleme_ucreti',
            field=models.CharField(choices=[('100 USD', '100 USD'), ('150 USD', '150 USD'), ('200 USD', '200 USD'), ('250 USD', '250 USD'), ('300 USD', '300 USD'), ('100 EUR', '100 EUR'), ('150 EUR', '150 EUR'), ('200 EUR', '200 EUR'), ('250 EUR', '250 EUR'), ('300 EUR', '300 EUR'), ('Diğer', 'Diğer')], default='100 USD', max_length=20),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_konum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='is',
            name='yukleme_ucretsiz_saat',
            field=models.IntegerField(choices=[(24, '24 Saat'), (48, '48 Saat'), (72, '72 Saat')], default=24),
        ),
        migrations.AlterField(
            model_name='is',
            name='durum',
            field=models.CharField(choices=[('Teklif', 'Teklif'), ('Planlandı', 'Planlandı'), ('Yüklemede', 'Yüklemede'), ('Yüklendi', 'Yüklendi'), ('Yolda', 'Yolda'), ('Limanda', 'Limanda'), ('Boşaltmada', 'Boşaltmada'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Teklif', max_length=50),
        ),
        migrations.AlterField(
            model_name='is',
            name='odeme_durumu',
            field=models.CharField(choices=[('Ödenmedi', 'Ödenmedi'), ('Kısmi Ödeme', 'Kısmi Ödeme'), ('Ödendi', 'Ödendi')], default='Ödenmedi', max_length=50),
        ),
    ]
