# Generated by Django 6.0.4 on 2026-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0014_rename_tasima1_gelen_fatura_tutari_is_elden_verilen_avans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='is',
            name='tasima1_gelen_fatura_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='is',
            name='tasima2_gelen_fatura_tutari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
